/**
 * Generates `app/track.js/snippet.generated.ts` from `snippet.source.ts`.
 *
 * Runs as `prebuild`, so `npm run build` always regenerates it and the committed
 * artifact can never silently drift from the source it was built from.
 *
 * esbuild is deliberately confined to this script rather than imported by the
 * route: it is a build tool with a native binary, and pulling it into the Next
 * server graph fails the build outright (webpack tries to parse its .d.ts).
 */
import { transformSync } from "esbuild";
import { writeFileSync } from "fs";
import { resolve } from "path";
import { SNIPPET } from "../app/track.js/snippet.source";

const OUT = resolve(import.meta.dirname, "../app/track.js/snippet.generated.ts");

const { code } = transformSync(SNIPPET, {
  minify: true,
  target: "es5",
  format: "iife",
});

// A minifier that returns something larger, or empty, has not done what we
// asked. Fail the build rather than ship a mystery.
if (!code || code.length >= SNIPPET.length) {
  throw new Error(
    `track.js minification produced ${code?.length ?? 0} bytes from ${SNIPPET.length}; refusing to write.`
  );
}

// The snippet is full of backticks-unsafe characters only if it contains them;
// JSON.stringify sidesteps template-literal escaping entirely.
writeFileSync(
  OUT,
  `// GENERATED by scripts/build-track-snippet.ts — do not edit.\n` +
    `// Source of truth: app/track.js/snippet.source.ts\n` +
    `export const SNIPPET_MIN = ${JSON.stringify(code)};\n`,
  "utf-8"
);

const saved = SNIPPET.length - code.length;
console.log(
  `track.js: ${SNIPPET.length} -> ${code.length} bytes (saved ${saved}, ${((100 * saved) / SNIPPET.length).toFixed(1)}%)`
);
